"use client";

import { SlideUp } from "@/components/animations/SlideUp";
import { GlassCard } from "@/components/ui/glass-card";
import { Target, Image as ImageIcon, WalletCards, BarChart3, ArrowRight, ShieldCheck } from "lucide-react";
import Link from "next/link";

export default function ForBrandsPage() {
  const steps = [
    {
      icon: <ImageIcon className="w-8 h-8 text-purple-light" />,
      title: "1. Upload Your Banners",
      description: "Provide your brand creatives and banners. We support multiple formats tailored for vertical video placement.",
    },
    {
      icon: <WalletCards className="w-8 h-8 text-blue-400" />,
      title: "2. Set Campaign Budget",
      description: "Define how much you want to spend. Our platform charges a transparent fee for executing the promotional campaign.",
    },
    {
      icon: <Target className="w-8 h-8 text-purple-light" />,
      title: "3. Automated Distribution",
      description: "Our AI matches your brand with relevant creators and automatically inserts your banners into high-performing reels.",
    },
    {
      icon: <BarChart3 className="w-8 h-8 text-blue-400" />,
      title: "4. Track Performance",
      description: "Monitor impressions, engagement, and ROI in real-time through your dedicated brand dashboard.",
    }
  ];

  const benefits = [
    {
      title: "Instant Deployment",
      description: "Launch campaigns across hundreds of creators simultaneously without individual negotiations.",
      icon: <Target className="w-6 h-6 text-primary" />
    },
    {
      title: "Performance-Based Spend",
      description: "You only pay for actual views and engagement generated by the creators.",
      icon: <BarChart3 className="w-6 h-6 text-primary" />
    },
    {
      title: "Brand Safety Assured",
      description: "Our AI ensures your banners only appear on content that aligns with your brand guidelines.",
      icon: <ShieldCheck className="w-6 h-6 text-primary" />
    }
  ];

  return (
    <div className="min-h-screen pt-32 pb-20 px-4 md:px-8 bg-background relative overflow-hidden">
      <div className="absolute top-1/4 right-0 w-[500px] h-[500px] bg-blue/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-1/4 left-0 w-[600px] h-[600px] bg-purple/10 rounded-full blur-[120px] pointer-events-none" />
      
      <div className="max-w-6xl mx-auto relative z-10">
        <SlideUp>
          <div className="text-center max-w-4xl mx-auto mb-20">
            <h1 className="text-5xl md:text-7xl font-bold mb-6">Massive Reach. Authentic Engagement. <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-light">Zero Negotiation.</span></h1>
            <p className="text-xl text-muted-foreground">
              Provide your banners and a budget. We handle the promotion across our vast network of highly-engaging creators.
            </p>
          </div>
        </SlideUp>

        {/* How It Works Section */}
        <div className="mb-32">
          <SlideUp delay={0.1}>
            <div className="text-center mb-16">
              <h2 className="text-4xl font-bold mb-4">How Campaigns Work</h2>
              <p className="text-lg text-muted-foreground">Launch scalable marketing campaigns in minutes.</p>
            </div>
          </SlideUp>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {steps.map((step, i) => (
              <SlideUp key={i} delay={0.2 + (i * 0.1)}>
                <GlassCard className="p-8 h-full border-border hover:border-primary/30 transition-colors">
                  <div className="w-16 h-16 rounded-2xl bg-secondary flex items-center justify-center mb-6">
                    {step.icon}
                  </div>
                  <h3 className="text-xl font-bold mb-3">{step.title}</h3>
                  <p className="text-muted-foreground">{step.description}</p>
                </GlassCard>
              </SlideUp>
            ))}
          </div>
        </div>

        {/* Benefits Section */}
        <div className="mb-32 bg-secondary/50 rounded-3xl p-8 md:p-16 border border-border">
          <SlideUp>
            <div className="text-center mb-12">
              <h2 className="text-4xl font-bold mb-4">Why Brands Choose Us</h2>
            </div>
          </SlideUp>
          <div className="grid md:grid-cols-3 gap-8">
            {benefits.map((benefit, i) => (
              <SlideUp key={i} delay={0.1 * i}>
                <div className="text-center">
                  <div className="w-12 h-12 rounded-full bg-background border border-border flex items-center justify-center mx-auto mb-4">
                    {benefit.icon}
                  </div>
                  <h3 className="text-xl font-bold mb-2">{benefit.title}</h3>
                  <p className="text-muted-foreground">{benefit.description}</p>
                </div>
              </SlideUp>
            ))}
          </div>
        </div>

        {/* CTA Section */}
        <SlideUp delay={0.3}>
          <GlassCard className="p-12 text-center bg-gradient-to-b from-blue-400/10 to-transparent border-blue-400/20">
            <h2 className="text-4xl font-bold mb-6">Ready to scale your marketing?</h2>
            <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
              Create your brand account today and launch your first automated influencer campaign.
            </p>
            <Link 
              href="/register" 
              className="inline-flex items-center justify-center gap-2 px-8 py-4 bg-primary text-primary-foreground font-bold rounded-full hover:bg-primary/90 transition-colors"
            >
              Create Brand Account
              <ArrowRight className="w-5 h-5" />
            </Link>
          </GlassCard>
        </SlideUp>
      </div>
    </div>
  );
}
